---
version: '3'
services:
  server:
    build: .
    image: index.docker.io/oaklabs/app-keyboard:latest
    network_mode: host
    devices:
      - /dev/dri
    volumes:
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/shm:/dev/shm
      - ./src:/app/src
    environment:
      - NODE_ENV=production
      - DISPLAY=:0
      