---
version: '3'
services:
  server:
    build: .
    image: index.docker.io/oaklabs/app-keyboard-python:latest
    network_mode: host
    stdin_open: true
    tty: true
    devices:
      - /dev/dri
    volumes:
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/shm:/dev/shm
      - /dev/input:/dev/input
    environment:
      - NODE_ENV=production
      - DISPLAY=unix:0.0
      
      
